version: '3'
services:

  winad-app:
    container_name: winad-app
    hostname: winad-app
    # image: winad:v0.1  ## image didn't compress
    image: winad.slim:latest ## compressed images
    restart: always
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true

  winad-redis:
    container_name: winad-redis
    hostname: winad-redis
    image: redis
    restart: always
    command: redis-server --requirepass your_redis_password
    tty: true
    stdin_open: true
